title: VueBlogify
banner: VueBlogify
description: Nuxt-based customizable static blogging platform
tabs:
  - name: 千字文
    to: /tag/千字文
  - name: 句子
    to: /tag/句子
  - name: 分类词汇
    to: /tag/分类词汇
posts:
  perPage: 5
author:
  login: polvcode
  avatar: 'https://en.gravatar.com/userimage/35152960/7140205ee2a71cbe54d3f2ac43c0370d.jpg?size=24'
  link: https://polvcode.dev
about: true
# You may set externals when dealing with Disqus and Google Analytics
# external:
#   disqus: vue-blogify
#   google:
#     analytics: UA-146246917-2
git:
  url: https://github.com/patarapolw/vue-blogify.git
  # See https://nuxtjs.org/faq/github-pages/
  base: /vue-blogify  # For Nuxt, need to set base when dealing with Github Pages
  # branch: gh-pages  # Always default to gh-pages
root: .data
outputDir: dist